[package]
org = "ballerinax"
name = "rabbitmq"
version = "3.2.0"
authors = ["Ballerina"]
keywords = ["service", "client", "messaging", "network", "pubsub"]
repository = "https://github.com/ballerina-platform/module-ballerinax-rabbitmq"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.11.0-20241112-214900-6b80ab87"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "./lib/amqp-client-5.18.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "rabbitmq-native"
version = "3.2.0"
path = "../native/build/libs/rabbitmq-native-3.2.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "constraint-native"
version = "1.6.0"
path = "./lib/constraint-native-1.6.0-20241113-090900-d276ad5.jar"

[build-options]
observabilityIncluded=true
